title: First-lesson page
email: mishona2017@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "First-lesson" # the subpath of your site, e.g. /blog
url: "https://mariya-Ill.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
# theme: 
# plugins:
markdown: kramdown
permalink: /:title:output_ext
theme: minima
